<a href="https://colab.research.google.com/github/ErenB02/minecraft2/blob/main/DM_Lab05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 05 - Data Mining
The goal of this lab is to preprocess a dataset to prepare it for a machine learning task.
The only libraty you can use is **pandas**.

We will be using the Titanic dataset. The goal is to predict if the person will survive or not.

### Load the dataset

In [46]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/andvise/DataAnalyticsDatasets/refs/heads/main/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,0,3,Mr. Owen Harris Braund,male,22.0,1,0.0,7.2500
1,2,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0.0,71.2833
2,3,1,3,Miss. Laina Heikkinen,female,26.0,0,0.0,7.9250
3,4,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,NaN,53.1000
4,5,0,3,Mr. William Henry Allen,male,35.0,0,0.0,8.0500
...,...,...,...,...,...,...,...,...,...
882,883,0,2,Rev. Juozas Montvila,male,27.0,0,0.0,13.0000
883,884,1,1,Miss. Margaret Edith Graham,female,19.0,0,0.0,30.0000
884,885,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2.0,23.4500
885,886,1,1,Mr. Karl Howell Behr,male,26.0,0,0.0,30.0000
886,887,0,3,Mr. Patrick Dooley,male,32.0,0,0.0,7.7500

### Encode the categorical variable into numerical
Focus on only those that you'll be using in your machine learning model

In [47]:
# Your code here
df.dtypes

#Focus only on Sex, Names will not be needed in model
df['Sex'].replace(['male', 'female'], [0,1], inplace=True)

#Remove what we will not use (DO WE NEED TO?)
#del df['Name']

#del df['PassengerId']

#Check
df.head(5)

<ipython-input-47-d1aa4a5f1c5e>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sex'].replace(['male', 'female'], [0,1], inplace=True)
<ipython-input-47-d1aa4a5f1c5e>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'].replace(['male', 'female'], [0,1], inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,0,3,Mr. Owen Harris Braund,0,22.0,1,0.0,7.2500
1,2,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,1,38.0,1,0.0,71.2833
2,3,1,3,Miss. Laina Heikkinen,1,26.0,0,0.0,7.9250
3,4,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,1,35.0,1,NaN,53.1000
4,5,0,3,Mr. William Henry Allen,0,35.0,0,0.0,8.0500

In [48]:
df.fillna(0, inplace=True) #Fill in NA values

### Split the dataset in 80% training and 20% test.

In [49]:
df.sample(len(df))

,PassengerId,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
748,749,0,3,Mr. Johannes Joseph Vande Velde,0,33.0,0,0.0,9.5000
835,836,1,1,Mr. Pierre Marechal,0,29.0,0,0.0,29.7000
742,743,0,3,Mr. Rossmore Edward Abbott,0,16.0,1,1.0,20.2500
2,3,1,3,Miss. Laina Heikkinen,1,26.0,0,0.0,7.9250
758,759,1,3,Mr. Hanna Assi Barah,0,20.0,0,0.0,7.2292
...,...,...,...,...,...,...,...,...,...
281,282,1,3,Mr. Edward Arthur Dorking,0,19.0,0,0.0,8.0500
84,85,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) B...,1,33.0,3,0.0,15.8500
551,552,1,3,Miss. Velin Ohman,1,22.0,0,0.0,7.7750
328,329,1,3,Miss. Agnes McCoy,1,28.0,2,0.0,23.2500
877,878,0,3,Mr. Johann Markun,0,33.0,0,0.0,7.8958

In [61]:
train_size = round(len(df)*0.8)

# Shuffle the dataset
df = df.sample(len(df))

df_train = df.iloc[:train_size]
df_test = df.iloc[train_size:]

### Divide the dataset between input variables (X) and output (y).
Select which columns should be kept for this particular task.

In [62]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare'],
      dtype='object')

In [63]:
# Your code here
input_columns = ['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare']
X_train = df_train[input_columns]
y_train = df_train['Survived']

X_test = df_test[input_columns]
y_test = df_test['Survived']

In [66]:
y_test.shape

(177,)

### Scale the data
Create 2 versions of the datasets, one scaled with a min-max scaler and onw with a standard scaler (using only pandas).

In [68]:
#X_train['Fare'] = (X_train['Fare'] - X_train['Fare'].min()) / (X_train['Fare'].max()- X_train['Fare'].min())
min_train = X_train.min()
max_train = X_train.max()

X_train = (X_train - min_train)/ (max_train - min_train)
X_train.describe()

,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,710.000000,710.000000,710.000000,710.000000,710.000000,710.000000
mean,0.657746,0.356338,0.367908,0.058979,0.060094,0.061837
std,0.415382,0.479254,0.176493,0.127957,0.129447,0.099584
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.500000,0.000000,0.258608,0.000000,0.000000,0.015469
50%,1.000000,0.000000,0.346569,0.000000,0.000000,0.026350
75%,1.000000,1.000000,0.469088,0.125000,0.000000,0.058556
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### What is the baseline for the accuracy?
What is the minimum accuracy a classifier should reach?

In [71]:
y_train.mode() # the most common class is 0

(y_test == 0).mean() #SHOULD BE 66 WHY 62 ?

0.6214689265536724